---

- hosts: 192.168.2.48
  tasks:
  - name: Comprimiendo archivos de sensor GDT en formato ZIP 
    archive:
      path:
        - /opt/splunk/etc
      dest: /tmp/GDT_cfg_Splunk.zip
      format: zip

- hosts: 192.168.2.48
  tasks:
    - name: Descargando backup de sensor en carpeta local "/tmp/"
      fetch:
        src: /tmp/GDT_cfg_Splunk.zip
        dest: /tmp/

- hosts: 192.168.2.48
  tasks:
    - name: Eliminando archivo.ZIP en Sensor GDT
      file:
        path: /tmp/GDT_cfg_Splunk.zip
        state: absent
