---

- hosts: 10.100.201.154
  tasks:
  - name: Comprimiendo archivos de sensor CAXDAC en formato ZIP 
    archive:
      path:
        - /opt/splunk/etc
      dest: /tmp/CAXDAC_cfg_Splunk.zip
      format: zip

- hosts: 10.100.201.154
  tasks:
    - name: Descargando backup de sensor en carpeta local "/tmp/"
      fetch:
        src: /tmp/CAXDAC_cfg_Splunk.zip
        dest: /tmp/

- hosts: 10.100.201.154
  tasks:
    - name: Eliminando archivo.ZIP en Sensor CAXDAC
      file:
        path: /tmp/CAXDAC_cfg_Splunk.zip
        state: absent
