---

- hosts: 172.23.103.138
  tasks:
  - name: Comprimiendo archivos de sensor Novasec en formato ZIP 
    archive:
      path:
        - /opt/splunk/etc
      dest: /tmp/Novasec_cfg_Splunk.zip
      format: zip

- hosts: 172.23.103.138
  tasks:
    - name: Descargando backup de sensor en carpeta local "/tmp/"
      fetch:
        src: /tmp/Novasec_cfg_Splunk.zip
        dest: /tmp/

- hosts: 172.23.103.138
  tasks:
    - name: Eliminando archivo.ZIP en Sensor Novasec
      file:
        path: /tmp/Novasec_cfg_Splunk.zip
        state: absent
