---

- hosts: 10.100.201.42
  tasks:
  - name: Comprimiendo archivos de sensor Previsora en formato ZIP 
    archive:
      path:
        - /opt/splunk/etc
      dest: /tmp/Previsora_cfg_Splunk.zip
      format: zip

- hosts: 10.100.201.42
  tasks:
    - name: Descargando backup de sensor en carpeta local "/tmp/"
      fetch:
        src: /tmp/Previsora_cfg_Splunk.zip
        dest: /tmp/

- hosts: 10.100.201.42
  tasks:
    - name: Eliminando archivo.ZIP en Sensor Previsora
      file:
        path: /tmp/Previsora_cfg_Splunk.zip
        state: absent
