---

- hosts: 172.16.30.63
  tasks:
  - name: Comprimiendo archivos de sensor NewNet en formato ZIP 
    archive:
      path:
        - /opt/splunk/etc
      dest: /tmp/NewNet_cfg_Splunk.zip
      format: zip

- hosts: 172.16.30.63
  tasks:
    - name: Descargando backup de sensor en carpeta local "/tmp/"
      fetch:
        src: /tmp/NewNet_cfg_Splunk.zip
        dest: /tmp/

- hosts: 172.16.30.63
  tasks:
    - name: Eliminando archivo.ZIP en Sensor NewNet
      file:
        path: /tmp/NewNet_cfg_Splunk.zip
        state: absent
